apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: sample-spring-boot-app-k8s-teste22
build:
  artifacts:
    - image: poc-backstage-sq/sample-spring-boot-app-k8s-teste22
      jib:
        args:
          - -Pjib
          - -DskipTests
manifests:
  rawYaml:
    - k8s/deployment.yaml
deploy:
  kubectl: {}